paths:
  data_dir: "./data"
  out_dir: "./out"
  nspl_csv: "./data/nspl.csv"
  rgc_ewni_xlsx: "./data/rgc_ewni.xlsx"
  rgc_scot_xlsx: "./data/rgc_scotland.xlsx"

geo_lookup:
  out_csv: "./out/GeoAreaLookup.csv"
  out_parquet: "./out/GeoAreaLookup.parquet"

  # If empty, script reads all sheets, but you can filter by pattern.
  ewni_sheets: []
  scotland_sheets: []

  # NEW: only process sheets whose name matches this regex
  sheet_name_pattern: "^[A-Z][0-9]{2}"

  column_map:
    code: ["Code", "GEOGCD", "GSS_CODE", "CODE", "LAD24CD", "WD24CD"]
    name: ["Name", "GEOGNM", "GEOGNMK", "GEOGNAME", "NAME", "LAD24NM", "WD24NM"]
    alternatename: ["Alt Name", "Alternate Name", "GEOGNMK", "ALTNAME", "LAD24NMW", "WD24NMW"]
    status: ["Status", "STAT", "GEOGSTAT", "ACTIVE", "STATUS"]

  per_sheet_overrides: {}

postcode_lookup:
  out_csv: "./out/PostcodeLookup.csv"
  out_parquet: "./out/PostcodeLookup.parquet"

  keep_columns:
    - pcds
    - oa21
    - lsoa21
    - msoa21
    - ladcd
    - lat
    - long

  join_name_for_codes:
    - oa21
    - lsoa21
    - msoa21
    - ladcd

  rename_final:
    pcds: Postcode
    oa21: OA21
    lsoa21: LSOA21
    msoa21: MSOA21
    ladcd: LADCD
    lat: Latitude
    long: Longitude

  use_duckdb: false
